core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name="contact"),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),

]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail')
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import checkout

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('checkout/', checkout, name='checkout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

item/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
      ordering = ('name',)
      verbose_name_plural = 'Categories'

    def __str__(self) -> str:
       return self.name
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name="items", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
       return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    inputClass = 'w-full p-3 mb-2 rounded-xl'

    username = forms.CharField(widget=forms.TextInput(attrs={
      'placeholder': 'Your username',
      'class': inputClass
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
      'placeholder': 'Your password',
      'class': inputClass
    }))


class SignupForm(UserCreationForm):
    inputClass = 'w-full p-3 mb-2 rounded-xl'

    username = forms.CharField(widget=forms.TextInput(attrs={
      'placeholder': 'Your username',
      'class': inputClass
    }))
    email = forms.EmailField(widget=forms.TextInput(attrs={
      'placeholder': 'Your email address',
      'class': inputClass
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
      'placeholder': 'Your password',
      'class': inputClass
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
      'placeholder': 'Repeat password',
      'class': inputClass
    }))
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

        

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.conf import settings
from .stripe import stripe

from item.models import Category, Item

from .forms import SignupForm

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items
    })

def contact(request):
    return render(request, 'core/contact.html')

def checkout(request):
    if request.method == 'POST':
        # Retrieve the token generated by Stripe.js
        token = request.POST.get('stripeToken')

        # Create a charge using the Stripe API
        try:
            charge = stripe.Charge.create(
                amount=1000,  # Amount in cents
                currency='usd',
                description='Example charge',
                source=token,
            )
            # Payment successful
            return render(request, 'core/stripe/success.html')
        except stripe.error.CardError as e:
            # Payment failed
            return render(request, 'core/stripe/error.html', {'error': e.error.message})

    return render(request, 'core/checkout.html', {'stripe_public_key': settings.STRIPE_PUBLIC_KEY})

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
    return render(request, 'core/signup.html', {
        'form': form
    })

def logout_view(request):
    logout(request)
    return redirect('/')

item/views.py
from django.shortcuts import render, get_object_or_404

from .models import Item

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title  %}{% endblock  %} - Puddle</title>
  </head>
  <body>
    <nav class="p-6 flex justify-between items-center border-b border-gray-200">
      <a href="{% url 'core:index' %}" class="font-semibold text-xl">Puddle</a>
      <div class="space-x-6">
        <a href="#" class="text-lg font-semibold hover:text-gray-500">New item</a>
        <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>
        
        {% if request.user.is_authenticated %}
        <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
        <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
        <a href="{% url 'core:logout' %}">Logout</a>

        {% else %}
        <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
        <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
        {% endif %}
      </div>
    </nav>
    <div class="p-6">{% block content %} {% endblock %}</div>
    <footer class="p-6 flex justify-between bg-gray-800">
      <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-semibold text-gray-400">About</h3>
        <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet</p>
      </div>
      <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
        <ul class="space-y-2">
          <li class="#"><a href="" class="text-lg text-teal-500 hover:text-teal-800">About</a></li>
          <li class="#"><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-800">Contact</a></li>
          <li class="#"><a href="" class="text-lg text-teal-500 hover:text-teal-800">Privacy policy</a></li>
        </ul>
      </div>
    </footer>
  </body>
</html>

core/templates/core/checkout.html
{% extends 'core/base.html' %} 
{% block title %} Checkout{% endblock  %}
{% block content %}
  <form method="post" action="{% url 'checkout' %}">
    {% csrf_token %}
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="{{ stripe_public_key }}"
        data-amount="1000"
        data-name="Example.com"
        data-description="Example charge"
        data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
        data-locale="auto"
        data-currency="usd">
    </script>
  </form>
{% endblock %}

core/templates/core/contact.html
{% extends 'core/base.html' %} 


{% block title %} Contact{% endblock  %}
{% block content %}
<h1>Contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %} 


{% block title %} Welcome{% endblock  %}
{% block content %}
  <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">
      Newest items
    </h2>
    <div class="grid grid-cols-3 gap-3">
      {% for item in items %}
        <div>
          <a href="{% url 'item:detail' item.id %}">
            <div class="">
              <img src="{{ item.image.url}}" alt="" class="rounded-t-xl">
            </div>
            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-2xl">{{ item.name}}</h2>
              <p class="text-gray-500">Price: {{item.price|floatformat:2}}$</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
  <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">
      Categories
    </h2>
    <div class="grid grid-cols-3 gap-3">
      {% for category in categories %}
      <div>
        <a href="#">
          <div class="p-6 bg-white rounded-b-xl">
            <h2 class="text-2xl">{{ category.name}}</h2>
            <p class="text-gray-500">{{ category.items.count}} items</p>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
Log in
{% endblock title %}

{% block content %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
  <h1 class="mb-6 text-3xl">Log in</h1>

  <form method='post' action="." class="">
    {% csrf_token %}
    
    <div class="mb-3">
      <label class="inline-block mb-2">Username</label><br/>
      {{ form.username }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Password</label><br/>
      {{ form.password }}
    </div>

    {% if form.errors or form.non_field_errors %}
      <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
          {{ field.errors }}
        {% endfor %}

        {{ form.non_filed_errors}}
      </div>
    {% endif %}
    <button class="mt-3 py-3 px-6 text-lg bg-teal-500 font-semibold hover:bg-teal-700 rounded-xl text-white">Submit</button>
  </form>
</div>
{% endblock content %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}
Sign up
{% endblock title %}

{% block content %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
  <h1 class="mb-6 text-3xl">Sign up</h1>

  <form method='post' action="." class="">
    {% csrf_token %}
    
    <div class="mb-3">
      <label class="inline-block mb-2">Username</label><br/>
      {{ form.username }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Email</label><br/>
      {{ form.email }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Password</label><br/>
      {{ form.password1 }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Repeat password</label><br/>
      {{ form.password2 }}
    </div>

    {% if form.errors or form.non_field_errors %}
      <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
          {{ field.errors }}
        {% endfor %}

        {{ form.non_filed_errors}}
      </div>
    {% endif %}
    <button class="mt-3 py-3 px-6 text-lg bg-teal-500 font-semibold hover:bg-teal-700 rounded-xl text-white">Submit</button>
  </form>
</div>
{% endblock content %}

core/templates/core/stripe/error.html
{% extends 'core/base.html' %} 
{% block title %} Success{% endblock  %}
{% block content %}
  <h1>Payment Failed</h1>
  <p>Error: {{ error }}</p>
{% endblock%}

core/templates/core/stripe/success.html
{% extends 'core/base.html' %} 
{% block title %} Success{% endblock  %}
{% block content %}
  <h1>Payment Successful!</h1>
{% endblock%}

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name}}{% endblock title %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
  <div class="col-span-3">
    <img src="{{ item.image.url}}" alt="" class="rounded-xl">
  </div>

  <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{item.name}}</h1>
    <p class="text-gray-500"><strong>Price:</strong> {{item.price|floatformat:2}}$</p>
    <p class="text-gray-500"><strong>Seller:</strong> {{item.created_by.username}}</p>
    {% if item.description %}
      <p class="text-gray-700 mt-3">
        <strong class="text-gray-500">Description:</strong><br/>
        {{ item.description }}
      </p>
    {% endif %}

    <a href="{% url 'checkout' %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Checkout</a>
  </div>

</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-12 text-2xl text-center">
    Related items
  </h2>
  <div class="grid grid-cols-3 gap-3">
    {% for item in related_items %}
      <div>
        <a href="{% url 'item:detail' item.id %}">
          <div class="">
            <img src="{{ item.image.url}}" alt="" class="rounded-t-xl">
          </div>
          <div class="p-6 bg-white rounded-b-xl">
            <h2 class="text-2xl">{{ item.name}}</h2>
            <p class="text-gray-500">Price: {{item.price}}$</p>
          </div>
        </a>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}